### PR TITLE
Update for 2.39+r52+gf8e4623421-1

### PR DESCRIPTION
**Pull request by ViNi-Arco**
Allows patches to be applied cleanly

### CODE REVIEW

**Comment by ViNi-Arco** [comment]
Don't merge this PR yet, I'll update rogue_company_reverts.patch to commit f8e462342189525e4605cf233b8f798d1c7f398d that Arch is using

**Comment by ViNi-Arco** [comment]
It's ready to merge now

**Comment by ViNi-Arco** [comment]
Strange, testing the [CI build](https://github.com/ViNi-Arco/glibc-eac/actions/runs/9039946604) Back 4 Blood no longer starts, with [2.39-4](https://github.com/ViNi-Arco/glibc-eac/actions/runs/8947963473) B4B it starts, I don't know if it was the ArchLinux update to GCC 14 or the new commit f8e462342189525e4605cf233b8f798d1c7f398d of GLIBC that broke B4B

**Comment by Tk-Glitch** [comment]
B4B used to work without this, right?

**Comment by ViNi-Arco** [comment]
> B4B used to work without this, right?

These PR are fine

Back 4 Blood worked with [2.39-4](https://github.com/ViNi-Arco/glibc-eac/actions/runs/8947963473) which was built with GCC 13 and against commit 31da30f23cddd36db29d5b6a1c7619361b271fb4, in ArchLinux latest [2.39+r52+gf8e4623421-1](https://github.com/ViNi-Arco/glibc-eac/actions/runs/9039946604) which is built with GCC 14 and against commit f8e462342189525e4605cf233b8f798d1c7f398d B4B doesn't start anymore.

ArchLinux has made these changes making it difficult to know which one brought the regression a commit between 31da30f23cddd36db29d5b6a1c7619361b271fb4 and f8e462342189525e4605cf233b8f798d1c7f398d, or GCC 14..

**Comment by Tk-Glitch** [comment]
Annoying. Thanks ViNi-Arco, I guess it's bisecting time.
:frog: :heart:

**Comment by dporki** [comment]
Squad is terminating with Unexpected Error 2 on the newest glibc-2.39+r52+gf8e4623421-1 build sadly. The 2-39-2 build works fine.

**Comment by Tk-Glitch** [comment]
So yeah, something definitely regressed :sweat:

**Pull request merged**
